#делаем сборку вначале на компе, а потом на сервер отправляю
FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
# Мы не копируем весь код через COPY, так как он примонтируется через volumes
EXPOSE 3010
# Запуск Vite с флагами для Docker
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3010"]